server:
  address: 'localhost:9000'

logger:
  log_level: 'debug'

db:
  dns: "postgresql://postgres:123456@localhost/gophkeeper?connect_timeout=10&sslmode=disable"
  connect_timeout: 2
  query_timeout: 3